### ISSUE TITLE
Cannot verify app signed without scheme v1

### ISSUE THREAD

**Issue by ttimasdf** [patrickfav/uber-apk-signer#8]
```
01. app-release.apk

	VERIFY
	file: /path/to/OnePlusExtension/app/release/app-release.apk
	checksum: b6061010215bdcd30b2971202b465d87c12feaac3492db821d55ed59a9f38146 (sha256)
	- zipalign verified
	- signature VERIFY FAILED (app-release.apk)
		ERROR: No JAR signatures

[Mon Feb 05 09:37:39 CST 2018][v0.8.3]
Successfully processed 0 APKs and 1 errors in 0.21 seconds.
```
This apk can be verified successfully by nougat/oreo for it's signed with scheme v2. It should be a expected behavior that an apk signed without v1 (/META-INF/CERT.*) is also valid.

Sample package available [here](https://github.com/ttimasdf/OnePlusExtension/releases/download/v1.3/app-release.apk).

**Comment by patrickfav** [comment]
I use Google's apk-signer for the actual signing and verifying so Im pretty sure, you will have the same output when using the official tool. That said AFAIK it is aware of the min/target SDK version in the AndroidManifest and if your minSDK is smaller than 24 (?) a apk signed without v1 will not be valid since it wont install on Android versions which do not know v2.

**Comment by ttimasdf** [comment]
Oh, many thanks. I barely noticed the importance of minSDKversion. 😅 My fault.
